<?php

namespace AppBundle\Repository;

/**
 * NationaliteUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationaliteUserRepository extends \Doctrine\ORM\EntityRepository
{
}
