<?php

namespace AppBundle\Repository;

/**
 * NbvueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NbvueRepository extends \Doctrine\ORM\EntityRepository
{
}
