<?php

namespace AppBundle\Repository;

/**
 * PostuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostuleRepository extends \Doctrine\ORM\EntityRepository
{
}
