# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER , ROLE_MEMBRE,ROLE_MODERATEUR
        ROLE_MEMBRE: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        our_users:
            entity: { class: AppBundle\Entity\User, property: email }
    firewalls:





        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/

            #form_login:

             #   provider: fos_userbundle
              #  check_path: fos_user_security_check
               # csrf_token_generator: security.csrf.token_manager
                #default_target_path: /login_ok

            guard:
                authenticators:
                    - app.security.login_form_authenticator

            #            form_login:
            #                csrf_token_generator: security.csrf.token_manager

            logout: true



            anonymous: true
            access_denied_url: /forbidden

    access_control:
    - {path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - {path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY}
    - {path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY}
    - {path: ^/admin, role: ROLE_ADMIN}
    - {path: ^/client, role: ROLE_MEMBRE}
    - {path: ^/login_ok, role: ROLE_USER}
    - {path: ^/moderateur,role: ROLE_MODERATEUR}


